function optMatrix = compute_circularcell_conv(...
        circularCell, temporalKernel)
    import smalltargetmotiondetectors.util.compute.compute_temporal_conv;
    optMatrix = compute_temporal_conv( ...
        circularCell.data, ...
        temporalKernel, ...
        circularCell.point);
end