function hModel = adjust_coef(hModel, modelName, speedCoef)
    switch modelName
        case 'ESTMD'
            propertiesList = {
                'hModel.hMedulla.hTm1.hGammaDelay.order', ...
                'hModel.hMedulla.hTm1.hGammaDelay.tau' ...
                };
        case {'DSTMD', 'STMDPlus'}
            propertiesList = {
                'hModel.hMedulla.hDelay4Mi1.hGammaDelay.order', ...
                'hModel.hMedulla.hDelay4Mi1.hGammaDelay.tau', ...
                'hModel.hMedulla.hDelay5Tm1.hGammaDelay.order', ...
                'hModel.hMedulla.hDelay5Tm1.hGammaDelay.tau', ...
                'hModel.hMedulla.hDelay6Tm1.hGammaDelay.order', ...
                'hModel.hMedulla.hDelay6Tm1.hGammaDelay.tau'
                };
        case 'ApgSTMD'
            propertiesList = {
                'hModel.hMedulla.hDelay4Mi1.hGammaDelay.order', ...
                'hModel.hMedulla.hDelay4Mi1.hGammaDelay.tau', ...
                'hModel.hMedulla.hDelay5Tm1.hGammaDelay.order', ...
                'hModel.hMedulla.hDelay5Tm1.hGammaDelay.tau', ...
                'hModel.hMedulla.hDelay6Tm1.hGammaDelay.order', ...
                'hModel.hMedulla.hDelay6Tm1.hGammaDelay.tau', ...
                'hModel.hPredictionPathway.intDeltaT' ...
                };
        case 'FracSTMD'
            propertiesList = {
                'hModel.hMedulla.hTm1.hGammaDelay.order', ...
                'hModel.hMedulla.hTm1.hGammaDelay.tau'...
                }; 
        case 'FeedbackSTMD'
            propertiesList = {
                'hModel.hMedulla.hTm1.hGammaDelay.order', ...
                'hModel.hMedulla.hTm1.hGammaDelay.tau', ...
                'hModel.hLobula.hGammaDelay.order', ...
                'hModel.hLobula.hGammaDelay.tau' ...
                };
        case 'FSTMD'
            propertiesList = {
                'hModel.hMedulla.hTm1.hGammaDelay.order', ...
                'hModel.hMedulla.hTm1.hGammaDelay.tau', ...
                'hModel.hFeedbackPathway.hGammaDelay.order', ...
                'hModel.hFeedbackPathway.hGammaDelay.tau' ...
                };

        otherwise
            return;
    end

    for nProperty = propertiesList
        property = nProperty{1};
        eval([property, ' = ', property, ' * speedCoef;']);
    end

end
